### ISSUE TITLE
Roadmap towards MVP seeder in Rust

### ISSUE THREAD

**Issue by superbaud** [superbaud/zcash-cotyledon#1]
- [ ] Start with a loop that connects, polls, then disconnects from a premade list of servers
- [ ] properly handle and classify errors while polling peers
- [ ] add serving of IP addresses/ports over gRPC/HTTP/DNS
- [ ] integrate gRPC/HTTP seeder client into zcashd/zebra
- [ ] keep track of per-peer reachability statistics (start simple at first)
- [ ] keep track of per-peer version statistics: we need to work with ZF to rework the zebra_network connection functions to return all the peer version metadata, the issue for this is https://github.com/ZcashFoundation/zebra/issues/4678
- [ ] poll peers for other peers, and add them to the list we're keeping track of
- [ ] classify peers appropriately by reachability / version
- [ ] test if peers can serve a reasonably recent (after any notable chain forks) zcash block (this lets us exclude stuff like ZelCash/flux that didn't change the network magic number)
- [ ] keep track of per-peer synchronization status: if they're synced to tip and if they have a reasonably recent (we can hardcode this) zcash block

**Comment by superbaud** [comment]
I have the multi-scale EWMA calculations working! (though to be perfectly honest I do not *quite* understand the role of the `count` and `weight` tracked variables) https://github.com/superbaud/zcash-cotyledon/commit/31fd4c7b9c975844a8c3ee8b435e4e01a5d5877c

**Comment by superbaud** [comment]
Running into something weird with the `Peers` replies -- I'm not getting multiple peers anymore:
```
Starting new connection: peer addr is 157.245.172.190:8233
peers response: Peers { peers: 1 }
peers is: [MetaAddr { addr: 157.245.172.190:8233, services: Some(NODE_NETWORK), untrusted_last_seen: Some(DateTime32 { timestamp: 1666049426, calendar: 2022-10-17T23:30:26Z }), last_response: None, last_attempt: None, last_failure: None, last_connection_state: NeverAttemptedGossiped }]
```

**Comment by superbaud** [comment]
OK, since the `getaddr` command seems to be weirdly rate-limited (by `AVG_ADDRESS_BROADCAST_INTERVAL`) -- let's not use that to check if the node is live (`BlocksByHash` isn't rate-limited at all).

**Comment by superbaud** [comment]
i think i want to slightly change how crawling works; by creating a pending work queue (of IPs to query) and having it be separate from the `HashMap` (which once i have some other stuff working, i'll figure out how to save/restore from disk, undecided yet whether to use `serde` or learn how to use `sqlite`) that keeps track of all the nodes about, and so we can add new peers into the work queue as we find them (and also add them into the `HashMap`) while we are doing crawling vs needing to separate and batch crawling and updating (because we can't modify the `HashMap` while we're iterating over it)

**Comment by superbaud** [comment]
We have DNS serving working!
